name = terrainreview
creative_mode = true
enable_damage = false
server_announce = false
max_block_send_distance = 16
max_simultaneous_block_sends_per_client = 16
server_unload_unused_data_timeout = 60
goanna_far_summary_cache_areas = 1024
goanna_far_log_stats = true
goanna_far_rendering = true
goanna_far_rendering_distance = 4096
goanna_far_provider_distance = 4096
goanna_far_pregenerate = false
tdl_nodes_per_pixel = 30
tdl_climate_stretch = 1
default_privs = interact, shout, fly, fast, noclip, teleport, give, settime
anticheat_flags = digging,interaction,nomovement
time_speed = 0
