// SPDX-License-Identifier: LGPL-2.1-or-later
// Per-view feature gates, with on defaults in project.godot.
#ifndef GOANNA_FEATURE_FLAGS
#define GOANNA_FEATURE_FLAGS
global uniform float goanna_render_water_waves;
global uniform float goanna_render_water_reflections;
global uniform float goanna_render_wet_surfaces;
global uniform float goanna_render_foliage_wind;
global uniform float goanna_render_grass_interaction;
global uniform float goanna_render_ice_detail;
global uniform float goanna_render_lava_detail;
#endif
