// SPDX-License-Identifier: LGPL-2.1-or-later
// Copyright (C) 2026 the Goanna contributors

#pragma once

// Sub node shape and per node damage, v3. Ported from Kythen's
// mods/kythen/core/radial_form.lua at commit 809475f (branch form/damage);
// docs/architecture/radial-form.md is the design, in that same repository.
//
// WHAT CHANGED FROM v1, AND WHY THIS FILE LOOKS DIFFERENT NOW. v1 measured
// damage as a three-axis inset from the CUBE's own six faces (the old
// `FormDisplacement`, `formInset`, `strike`, `FormDig`). That could never
// damage a thin layer or a ramp correctly: a blow on a 1/16 moss layer's top
// landed on the CUBE's top face, a whole 15/16 of a node above the layer's
// real surface, and removed nothing the layer actually had. v3 measures
// damage from the SHAPE'S OWN surface instead: `formBaseline` finds, once per
// distinct base shape, a carve centre (`FormBaseline::centre`) and a present
// position per each of the twenty six control directions
// (`FormBaseline::present`): how far that shape's OWN surface actually sits
// from the centre. Per node damage is then a sparse `FormDamage`: a fraction
// (`delta`) that narrows a control's present position, and a local pit
// (`crater`) carved as a sphere or cube around wherever that control
// currently sits. The v1 displacement model is gone entirely; there is one
// damage model, not two.
//
// TWO KINDS OF BASE SHAPE THIS FILE SERVES.
//
//   1. `RadialForm`: Kythen's own authored primitive, up to twenty six
//      convex half space plane offsets (`box`), plus radial extents and axial
//      bores for the older carve/dig field. `formBaseline(RadialForm)`
//      derives centre and present positions from it. This exists so the
//      reference vectors this file is checked against (generated by asking
//      the Lua for cube, moss layer, ramp and mound cases) can be reproduced
//      exactly.
//
//   2. Arbitrary resolved node boxes: what a Kythen mound, a Mineclonia
//      slab or a stair actually arrives as over the ordinary Luanti protocol:
//      `node_box.fixed` or `node_box.connected`, already resolved for this
//      node's own neighbours by the client that already draws it.
//      `formBaselineFromBoxes` derives the same centre and present positions
//      from that box list directly, with no RadialForm and no game specific
//      shape catalogue involved. This is what the mesher uses for every
//      nodebox drawtype, and what a plain cube's trivial closed form baseline
//      is a special case of.
//
// Both feed the SAME strike, damage test, connectivity, stage and wire codec,
// which is the whole point: one rule, applied to whatever base shape a node
// happens to have.

#include <cstdint>
#include <functional>
#include <string>
#include <vector>

namespace goanna {

// Twenty six directions: six face normals, twelve edge midpoints, eight corner
// diagonals, the 26 neighbourhood of a cube. Order is six faces, THEN eight
// corners, THEN twelve edges. This is Kythen's own wire order
// (`radial_form.lua`'s `M.PLANES`: `M.DIRECTIONS`, six faces then eight
// corners, with the twelve edges appended after), and it must not be
// rearranged: the sparse codec's presence mask is indexed by it, and a port
// that puts edges before corners encodes a different byte string for the same
// damage. (v1's own history: this file's `kPlane` table once had edges before
// corners, and nothing noticed for a long time because most reads are order
// free; only the sparse codec, indexed by position, ever saw it.)
constexpr int FORM_PLANE_COUNT = 26;

// The thirteen bore axes: every one of the twenty six plane directions paired
// with its opposite, because a hole has no front and back. Three through the
// faces, six through the edge midpoints, four through the body diagonals.
constexpr int FORM_BORE_COUNT = 13;

// A control's key, exactly as Kythen's Lua names it ("xn", "ppp", "xnyp", ...),
// in `FORM_PLANE_COUNT` order. Used to parse the reference JSON and to build
// human readable diagnostics; nothing on the hot path reads it.
const char *controlKey(int index);
// -1 if `key` is not one of the twenty six control names.
int controlIndexForKey(const std::string &key);
// The six face control indices, in Kythen's `M.FACES` order
// (xn, xp, yn, yp, zn, zp). The `cube` metric's strike pool and
// `formDamageSolid`'s axis test both read only these six.
extern const int kFaceControl[6];

// A box in node local coordinates on [-0.5, 0.5], as a nodebox would give it.
struct FormBox {
    float x1, y1, z1, x2, y2, z2;
};

// Is this point, in node local coordinates, inside any of these boxes? The
// base shape test for a nodebox drawn node: no RadialForm, no catalogue, just
// whatever boxes this node's own definition (and its live neighbours, for a
// connected nodebox) already resolved to.
bool pointInBoxes(const std::vector<FormBox> &boxes, float px, float py, float pz);

// --------------------------------------------------------------------------
// RadialForm: Kythen's authored primitive (box/extents/bore), kept only so
// the reference vectors generated from the Lua can be reproduced exactly.
// The mesher never constructs one: a Goanna client only ever sees a node's
// RESOLVED boxes over the protocol, never this.
// --------------------------------------------------------------------------

struct RadialForm {
    float origin[3] = {0.0f, 0.0f, 0.0f};
    // Signed plane offset per control, [-1, 1]. 1 = untouched (the plane
    // touches the node and cuts nothing); default is a full cube.
    float box[FORM_PLANE_COUNT];
    // Authored radial carve depth per control, in node units; negative means
    // absent (the plane's own reach applies instead).
    float extents[FORM_PLANE_COUNT];
    // Bore half width per axis, node units, 0 = no hole.
    float bore[FORM_BORE_COUNT] = {
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
        0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f
    };

    RadialForm() {
        for (int i = 0; i < FORM_PLANE_COUNT; ++i) { box[i] = 1.0f; extents[i] = -1.0f; }
    }
};

// The authored shape test only: `box`, `extents`, `bore`. Never per node
// damage, which is a separate, later test over a shape's own baseline
// (`formDamageSolid`), not over this.
bool formSolid(const RadialForm &form, float px, float py, float pz);

// The occupancy grid, resolution^3, indexed k*n*n + j*n + i.
std::vector<bool> formGrid(const RadialForm &form, int resolution);

// Fraction of occupied subcubes at the requested resolution: a shape's own
// pristine volume, which `formProgress` measures damage against.
float formVolume(const RadialForm &form, int resolution);

// Greedy boxes for a baked nodebox. Boxes come out in node units on
// [-0.5, 0.5], ready for `node_box.fixed`.
std::vector<FormBox> formBoxes(const RadialForm &form, int resolution);

// --------------------------------------------------------------------------
// The carve centre and present position: `FormBaseline`. Two derivations,
// one shared algorithm underneath (see the .cpp's `computeBaseline`).
// --------------------------------------------------------------------------

struct FormBaseline {
    float centre[3] = {0.0f, 0.0f, 0.0f};
    // How far this shape's own surface sits from `centre`, along each of the
    // twenty six control directions, in node units.
    float present[FORM_PLANE_COUNT] = {};
};

// From Kythen's authored primitive. Closed form when the box is full and
// there is no bore (a plain cube, the overwhelmingly common case); otherwise
// found by marching out from the shape's own volume centroid and bisecting
// against `formSolid`, exactly as `radial_form.lua`'s `M.baseline` does.
FormBaseline formBaseline(const RadialForm &form);

// From a node's own resolved boxes: what every nodebox drawn node in a real
// game gives a Goanna client. The same march and bisect, over
// `pointInBoxes` instead of `formSolid`.
FormBaseline formBaselineFromBoxes(const std::vector<FormBox> &boxes);

// The trivial baseline of a plain, unmodified cube: centre at the origin, and
// every control's present position is exactly its own support distance (a
// face half a node, an edge 1/sqrt(2) of that, a corner 1/sqrt(3)). Closed
// form, no march: this is what `drawSolidNode` uses for an NDT_NORMAL node,
// which is never a RadialForm or a box list at all.
FormBaseline formBaselineForCube();

// The control whose direction is most aligned with (nx, ny, nz), and its
// present position: the "how far material reaches toward the struck surface"
// a caller scales a blow's depth against, so the same fractional bite takes
// the same fraction of what is actually there whether that is a cube face at
// 0.5 or a 1/16 layer's top at 0.03.
float formReferencePresent(const FormBaseline &baseline, float nx, float ny, float nz);

// --------------------------------------------------------------------------
// Per node damage: sparse, stored, and the only thing that changes as a
// block is worked. `delta` and `crater` are indexed like `present`; an
// absent control is 0 in both, which is what makes an untouched node's
// damage encode to nothing.
// --------------------------------------------------------------------------

enum class FormMetric { Sphere, Cube };

struct FormDamage {
    float delta[FORM_PLANE_COUNT] = {};
    float crater[FORM_PLANE_COUNT] = {};
    // The resolution and metric this damage was struck at. Stored on the
    // node (via the wire codec below) because a renderer needs nothing about
    // the node's type to decode or draw it, only the bytes on the node
    // itself.
    int resolution = 8;
    FormMetric metric = FormMetric::Sphere;

    bool empty() const {
        for (int i = 0; i < FORM_PLANE_COUNT; ++i) {
            if (delta[i] > 0.0f || crater[i] > 0.0f) { return false; }
        }
        return true;
    }
};

// The cap a crater's stored byte can reach: a plain node length, not a
// fraction of anything (see radial-form.md, "Craters"). sqrt(3)/2 is the
// farthest any point in a node can be from another point inside it.
constexpr float kCraterMax = 0.9f;

// Distribute one blow across the nearest controls, splitting depth between
// the two operators (half narrows the struck controls' own radius, half
// grows a crater centred on wherever that control currently sits), gated
// twice: by the struck surface's own normal (which controls are reachable at
// all, and it never widens) and by the hit's own direction from the carve
// centre (which discriminates quadrants the normal alone cannot). The
// control most aligned with the normal never loses its seat, even if the
// plain nearest four search would have dropped it: the dead centre rule
// that keeps a dead centre hit depositing where it visibly landed.
//
// No-op (returns `damage` unchanged) for a non-finite or non-positive depth,
// a non-finite hit point, or a hit exactly at the carve centre (no direction
// to strike along).
FormDamage formStrike(const FormBaseline &baseline, FormDamage damage,
        float px, float py, float pz, float depth, float nx, float ny, float nz);

// Is this point, in node local coordinates, still material once per node
// damage narrows the base shape? ANDed by every caller with the base shape's
// own solidity test (`formSolid` or `pointInBoxes`), so an untouched node
// (empty damage) reads exactly as the base shape.
bool formDamageSolid(const FormBaseline &baseline, const FormDamage &damage,
        float px, float py, float pz);

// Drop every subcube not six-connected (face adjacent) to the cell holding
// (anchor_x, anchor_y, anchor_z), on a copy of `grid`. Falls back to the
// nearest still solid cell if the anchor's own cell has been hollowed out.
std::vector<bool> formConnected(const std::vector<bool> &grid, int n,
        float anchor_x, float anchor_y, float anchor_z);

// The full per node occupancy grid: `baseSolid` (the base shape) AND
// `formDamageSolid` (delta and crater), then `formConnected` from
// `baseline.centre`. `baseSolid` is `formSolid(form, ...)` for a RadialForm
// base shape, `pointInBoxes(boxes, ...)` for a nodebox one, or a function
// that always returns true for a plain cube.
std::vector<bool> formGridDamaged(const std::function<bool(float, float, float)> &baseSolid,
        const FormBaseline &baseline, const FormDamage &damage, int n);

// Fraction of `formGridDamaged` that is still solid.
float formVolumeDamaged(const std::function<bool(float, float, float)> &baseSolid,
        const FormBaseline &baseline, const FormDamage &damage, int n);

// Below this fraction of a shape's OWN material the node is worn through.
// Read by `formStage` and by whatever caller decides when a node breaks, so
// the two can never disagree about how close a block is to breaking.
constexpr float kFormRemains = 0.35f;

// How far gone a node's stored damage has taken it, 0 (pristine) to 1 (at or
// past `kFormRemains`), as a fraction of the shape's own material.
// `pristineVolume` is the base shape's own fraction of the grid (1.0 for a
// plain cube; `formVolume(form, n)` for a RadialForm; the nodebox
// equivalent for a box list); `connectedVolume` is `formVolumeDamaged`'s
// result. Matches `radial_form.lua`'s `M.progress` exactly.
float formProgress(float pristineVolume, float connectedVolume);

// Five frames, matching the engine's own `crack_anylength.png` (a 16x80
// filmstrip; `game.cpp` derives the frame count as its own height over its
// own width). `formStage` reuses this count so a renderer that already knows
// how to draw a dig crack can draw a worked block's own accumulated one with
// the same asset.
constexpr int kCrackFrames = 5;

// The crack stage a node's stored damage has earned, 0 to `kCrackFrames - 1`.
// 0 only when `damage` is entirely empty; 1 as soon as anything is stored,
// however small, because storage existing at all is real progress before any
// whole subcube has crossed a line; the remaining frames spread across the
// rest of `formProgress`'s own range, so frame `kCrackFrames - 1` is reached
// exactly when the node is due to break.
int formStage(bool hasDamage, float pristineVolume, float connectedVolume);

// --------------------------------------------------------------------------
// The wire codec. Must stay byte identical to `radial_form.lua`'s `M.encode`
// and `M.decode` (format 4 at commit 809475f: the byte layout is unchanged
// from format 3, but see the header comment on `FormDamage` and
// `formDamageSolid` for what changed underneath it). The same node is
// written by one implementation and read by the other.
//
// Layout: a version byte (3), a header byte (two bits of resolution code,
// one bit of metric), four bytes of control presence (26 bits, lowest
// control first), then per present control one field byte (bit 0 delta, bit
// 1 crater) and one byte per field it names, in that order.
//
// Any v1 or v2 string, or one this cannot recognise, decodes as pristine
// (an empty `FormDamage`) rather than erroring: that is what every untouched
// node, and every node an older world still carries, already has.
// --------------------------------------------------------------------------

std::string encodeForm(const FormDamage &damage);
FormDamage decodeForm(const std::string &bytes);

// --------------------------------------------------------------------------
// Carves the server has told this client about, for nodes it is not digging.
// Keyed by world node position; a lock guarded store, snapshotted per block
// for meshing exactly as v1's did: the mesher runs on several worker threads
// at once and must never touch the shared store directly.
// --------------------------------------------------------------------------

void carveStoreSet(int x, int y, int z, const FormDamage &damage);
void carveStoreClear(int x, int y, int z);
bool carveStoreGet(int x, int y, int z, FormDamage &out);
bool carveStoreEmpty();

// One block's carves, snapshotted for meshing. Positions are node coordinates
// relative to the block, so a lookup is a comparison and not arithmetic.
struct CarveSnapshot {
    struct Entry { int16_t x, y, z; FormDamage damage; };
    std::vector<Entry> entries;
    const FormDamage *find(int x, int y, int z) const {
        for (const Entry &e : entries) {
            if (e.x == x && e.y == y && e.z == z) { return &e.damage; }
        }
        return nullptr;
    }
};

// Fill `out` with the carves inside the block whose low corner is the given
// node position. Takes the store's lock once.
void carveSnapshot(int block_x, int block_y, int block_z, CarveSnapshot &out);

// The snapshot the current thread is meshing against, or null. Thread local
// because several mesh workers run at once and each is on a different block.
extern thread_local const CarveSnapshot *g_goanna_carve_block;

// --------------------------------------------------------------------------
// Local (client side) dig prediction: the carve Goanna draws while a player
// is digging, before the server has confirmed anything. Resumed from any
// carve already stored on the node, and advanced by discrete blows as
// `MiningCycle` contacts land (see goanna_mining_cycle.h), one `formStrike`
// per contact.
//
// EACH BLOW'S DEPTH IS CHOSEN BY SEARCH, not read from a game's own tuning
// (`BLOW`, tool wear scaling): Goanna is a generic renderer and has no access
// to a game's `core.get_dig_params`. Mirroring v1's own contract instead,
// which needed none of that either: the search picks the smallest uniform
// depth that brings the connected volume down to `pristine * (1 - progress)`,
// so the dig always ends with the node empty exactly when the engine's own
// dig timer says it is done, whatever a game's own server side tuning would
// have produced. This can disagree with a game's own eventual stored bytes in
// the details of WHICH controls carried the depth; it cannot disagree on
// when the node is gone.
// --------------------------------------------------------------------------

struct FormDig {
    FormBaseline baseline;
    FormDamage damage;
    float pristine_volume = 1.0f;
    float applied_progress = 0.0f;
    float remaining_volume = 1.0f;
    int initial_cells = -1;

    // Begin (or resume, if `damage` already carries stored bytes) a dig
    // against a plain cube.
    void beginCube();
    // Begin (or resume) a dig against a node's own resolved boxes.
    void beginBoxes(const std::vector<FormBox> &boxes, int resolution);

    // Advance to `progress` (0 to 1, monotonic; a lower value than already
    // applied is a no-op), striking at (px, py, pz) with surface normal
    // (nx, ny, nz). Returns true if this call changed anything.
    bool advance(float progress, float px, float py, float pz,
            float nx, float ny, float nz);

private:
    std::function<bool(float, float, float)> base_solid_;
    int resolution_ = 8;
};

// One greedy rectangle of an exposed, damaged surface. Face order matches
// Luanti: +Y, -Y, +X, -X, +Z, -Z. backing >= 0 identifies the neighbour whose
// own material closes an opened boundary; face is then the opposite normal.
// Unchanged from v1: this operates on a plain occupancy grid (whatever
// produced it), never on a RadialForm or a FormDamage directly.
struct FormSurface {
    FormBox box;
    int face;
    int backing = -1;
};
std::vector<FormSurface> formSurfaces(const std::vector<bool> &grid, int n,
        uint8_t visible_boundary = 63, uint8_t backing_boundary = 0);

} // namespace goanna
